<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Refrigerators</name>
   <tag></tag>
   <elementGuidId>ed32a17f-3fc4-48a8-b1f2-d92f8aebed17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-content-1']/ul/li/a/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.isGlobalSiteTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>9cdde864-f372-49d0-847b-cf6f9a93dfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>isGlobalSiteTitle</value>
      <webElementGuid>505cf257-dcce-4cea-8c90-47bc0b284d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Refrigerators</value>
      <webElementGuid>6d3623a1-4a81-4c71-86c8-13526f22cf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-content-1&quot;)/ul[@class=&quot;ul-clear category-list&quot;]/li[1]/a[1]/h2[@class=&quot;isGlobalSiteTitle&quot;]</value>
      <webElementGuid>70d1d9a2-e086-44a8-8097-f502fb08b60e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li/a/h2</value>
      <webElementGuid>0ad180b5-e83e-4cd1-bdeb-741ee5fb1d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>79c3e32e-4d4a-4f25-9a01-f670657da74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '
                                                Refrigerators' or . = '
                                                Refrigerators')]</value>
      <webElementGuid>01a9af92-05a2-42d9-9ddb-7ebcac2382f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
