<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_lazy loaded</name>
   <tag></tag>
   <elementGuidId>c1d8cec5-f276-40eb-bba3-3b8a2bd6eba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-content-1']/ul/li[2]/a/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a > figure.responsive > img.lazy.loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>86e93888-b895-4845-94b3-ee398ad05c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy loaded</value>
      <webElementGuid>2d135d30-226d-4672-9d0e-b8cf56ebaa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>/medias/Image-16-250x250.png?context=bWFzdGVyfHJvb3R8MTExNjN8aW1hZ2UvcG5nfGFHWTVMMmhoTnk4eE1EVTVPRGt4TURjeU1qQTNPQzlKYldGblpTQXhOaUF0SURJMU1IZ3lOVEF1Y0c1bnwzM2I0YTA1ODhjMDY0M2MwMGQ1NzVjYzg0MDc4YmUxNWY5MjcyNmFiYjQ0M2EzYjc3YjQwMTkzNmQ2ZmU4ODM4 1x</value>
      <webElementGuid>55115247-9cac-4302-83e0-b7922004dd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/medias/Image-16-250x250.png?context=bWFzdGVyfHJvb3R8MTExNjN8aW1hZ2UvcG5nfGFHWTVMMmhoTnk4eE1EVTVPRGt4TURjeU1qQTNPQzlKYldGblpTQXhOaUF0SURJMU1IZ3lOVEF1Y0c1bnwzM2I0YTA1ODhjMDY0M2MwMGQ1NzVjYzg0MDc4YmUxNWY5MjcyNmFiYjQ0M2EzYjc3YjQwMTkzNmQ2ZmU4ODM4 1x</value>
      <webElementGuid>d746221f-7af6-405e-85d3-0b6c571e60cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3f019e0-4a5d-45a0-8375-a157d828fcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-content-1&quot;)/ul[@class=&quot;ul-clear category-list&quot;]/li[2]/a[1]/figure[@class=&quot;responsive&quot;]/img[@class=&quot;lazy loaded&quot;]</value>
      <webElementGuid>d1621bd6-3317-43a2-88d6-170d86d6947a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li[2]/a/figure/img</value>
      <webElementGuid>2b0af1e3-016d-49bb-93e2-e64ed91efc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a/figure/img</value>
      <webElementGuid>fa4c5f5d-465f-4766-bbed-efa78f7d74eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li/a/figure/img</value>
      <webElementGuid>8d0cfa88-f6c8-4a9a-8c7b-6bd8c1248d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/a/figure/img</value>
      <webElementGuid>66e72ac3-cc5e-42d0-864d-75340a3d70ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
