<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Freezers</name>
   <tag></tag>
   <elementGuidId>513a3729-f63a-45f7-a386-7f86716b97d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='site-main']/div/div/div[2]/div[4]/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pnl-left > h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>eda9b4ca-2546-4803-953e-afc810e229e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Freezers</value>
      <webElementGuid>384ff640-94e2-4ff9-a49e-870372be9d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-main&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 productGridPage-page&quot;]/div[@class=&quot;top-panel container-max-1200&quot;]/div[@class=&quot;pnl-left&quot;]/h1[1]</value>
      <webElementGuid>61ae37b0-b250-41d7-b900-76d0052866ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='site-main']/div/div/div[2]/div[4]/div/h1</value>
      <webElementGuid>1dc064a0-b9f1-4ad9-ba6e-484834ff9401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/h1</value>
      <webElementGuid>c9d909be-afea-4b28-a819-1e9eb02011d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
            Freezers' or . = '
            Freezers')]</value>
      <webElementGuid>58ba6001-57fb-4d9a-a31e-a6bc459c72c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
