<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_lazy loaded</name>
   <tag></tag>
   <elementGuidId>7593b450-55e1-4c00-807f-9146d2442e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-content-1']/ul/li[2]/a/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a > figure.responsive > img.lazy.loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e08b4573-f23a-4689-b067-e377b88755e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy loaded</value>
      <webElementGuid>ee690662-a1d5-42aa-9126-c8a2ca3a2565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>/medias/Image-18-250x250.png?context=bWFzdGVyfHJvb3R8NDE1NjF8aW1hZ2UvcG5nfGFEQmlMMmc0TlM4eE1EVTVPVGcwTkRZeE1EQTNPQzlKYldGblpTQXhPQ0F0SURJMU1IZ3lOVEF1Y0c1bnwyYjlkNTNiMTVmZjU1Zjg3OWY1MmU0MGQ3YzExZTMwMTMwMTBjZjQzN2JlZmMwOTAyMWI3Yzg2M2E0NjIwMDUy 1x</value>
      <webElementGuid>dafb6f2d-53e3-4d19-8a9a-1adf29cc6b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/medias/Image-18-250x250.png?context=bWFzdGVyfHJvb3R8NDE1NjF8aW1hZ2UvcG5nfGFEQmlMMmc0TlM4eE1EVTVPVGcwTkRZeE1EQTNPQzlKYldGblpTQXhPQ0F0SURJMU1IZ3lOVEF1Y0c1bnwyYjlkNTNiMTVmZjU1Zjg3OWY1MmU0MGQ3YzExZTMwMTMwMTBjZjQzN2JlZmMwOTAyMWI3Yzg2M2E0NjIwMDUy 1x</value>
      <webElementGuid>4cf97163-f3c7-4fd0-b034-4a4765256406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>465ff10e-4edb-4812-b60f-6bf234f67c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-content-1&quot;)/ul[@class=&quot;ul-clear category-list&quot;]/li[2]/a[1]/figure[@class=&quot;responsive&quot;]/img[@class=&quot;lazy loaded&quot;]</value>
      <webElementGuid>c54c9f14-c930-4e02-9094-d9dac29a71b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li[2]/a/figure/img</value>
      <webElementGuid>19fb63dc-5f5f-4a82-a37d-54e3ebe8d226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a/figure/img</value>
      <webElementGuid>cad3977e-6db3-4ef4-93d0-3f8e844b2f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li/a/figure/img</value>
      <webElementGuid>511ffa0b-01d6-475d-a0a0-01cacfab6435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/figure/img</value>
      <webElementGuid>b651e95d-12de-4939-8634-71765e5a99ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
