<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>655c2ad9-b763-4ca7-b65c-a3878b371a3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notifiers']/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a58b308-590b-4ae1-9438-4b11528d0b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-dark</value>
      <webElementGuid>4cad8c73-f7e0-46f8-be5a-95df4a2cdaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>0a10dc81-9058-4e6a-bfae-0a2cea1c9ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account/notifications</value>
      <webElementGuid>7b456684-b182-4336-b894-ccf795199881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>18fc2cdc-c79f-4517-a367-e50df74165dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notifiers&quot;)/div[@class=&quot;ntf-footer js-ntf-footer&quot;]/a[@class=&quot;btn btn-outline-dark&quot;]</value>
      <webElementGuid>672d8339-d4a8-401f-b1f0-63b51807bf80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notifiers']/div[3]/a</value>
      <webElementGuid>2d46e95f-190b-4eb1-bd7b-4917cc07925e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/my-account/notifications')]</value>
      <webElementGuid>0e02c511-cf0a-42f6-aef9-5368ebef7971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>260a6e4e-e638-458c-be76-5cfdd2c638a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Login' and @href = '/my-account/notifications' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>29210aca-b240-4ab2-a699-9a99f9a2c445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
