<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Notifications</name>
   <tag></tag>
   <elementGuidId>d1dfa7bb-25a8-482e-a914-a3e0246b0be9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notifiers']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ntf-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c6d99149-10c3-48ef-a92f-64728d710ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ntf-title</value>
      <webElementGuid>a7e572d4-8755-4930-953c-3229ac26ce70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Notifications</value>
      <webElementGuid>47b77383-7902-4d4c-8200-6c37b2c5fcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notifiers&quot;)/div[@class=&quot;ntf-header&quot;]/div[@class=&quot;ntf-title&quot;]</value>
      <webElementGuid>bd5663f5-558b-4231-bb2c-c42e2a44f657</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notifiers']/div/div</value>
      <webElementGuid>46017abd-9b6e-41af-b630-2122faf0b4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>96379b0b-8a33-4e37-9e43-4f3beba34542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                Notifications' or . = '
                Notifications')]</value>
      <webElementGuid>fa05f30b-e4b6-4869-802e-7d8487945585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
