<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search</name>
   <tag></tag>
   <elementGuidId>c90e4083-44b7-49be-8477-07e9fec9bf26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='site-header']/div/div/div/div[4]/a[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>472dcb5d-8a60-436d-918f-4af2705385d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>placeholder</value>
      <webElementGuid>70dca18e-f1dc-4770-942a-04945ae793f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>4b01c89e-e811-470e-8cc4-f97a9420ded2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;header-top se-item&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-3 col-lg-5 col-right&quot;]/a[@class=&quot;btn-search js-ov-trg d&quot;]/div[@class=&quot;f-input&quot;]/div[@class=&quot;placeholder&quot;]</value>
      <webElementGuid>bf765e53-fcd0-4a8d-8a65-925f78346760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='site-header']/div/div/div/div[4]/a[2]/div/div[2]</value>
      <webElementGuid>958ee103-68b2-4b76-8e0c-338c90d5af0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div[2]</value>
      <webElementGuid>4ca6013f-02dc-46a0-ba45-dc185c4d0299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>876f4082-7671-480f-ac2b-8c9cc4102791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
