<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divoverlay</name>
   <tag></tag>
   <elementGuidId>42bcb9bb-683f-4273-b7d0-c7043823d895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overlay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8b39b52-43dc-4847-b00c-632962dac1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overlay</value>
      <webElementGuid>50255e9b-73f1-493e-ae7b-f1cd1cea5d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlay&quot;)</value>
      <webElementGuid>343a5855-63b1-4e83-84dc-71c21eb4cc36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='overlay']</value>
      <webElementGuid>456954f6-86ba-49bd-b5bc-2206518db89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>140da9a4-dde6-45dc-82b7-05fc112ceac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'overlay']</value>
      <webElementGuid>8f49ef49-95ce-4b67-aeeb-1d8264d57b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
