<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_lazy loaded</name>
   <tag></tag>
   <elementGuidId>da0ac607-26d7-4734-8117-d084bd6670fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='nav-menu-category']/ul[2]/li[5]/a/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Kitchen Appliances&quot;] > figure.responsive > img.lazy.loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f0954830-b6fe-4dc2-a88d-48ebaf5e4974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy loaded</value>
      <webElementGuid>fbff865a-6a9d-4e2b-8036-d3492ab153a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>/medias/Cooking-Appliances.png?context=bWFzdGVyfHJvb3R8NzY4NzR8aW1hZ2UvcG5nfGFEQm1MMmczT1M4eE1EVTVORFF3TlRZME5qTTJOaTlEYjI5cmFXNW5MVUZ3Y0d4cFlXNWpaWE11Y0c1bnxiMmUyYjgzYWQ3M2IyMDhkNjZhYjdmYTQ5ZGVlYTUxMjUwZjkxNjUyZmZlNGI0MjhkOGI3ZDlmOTQ1MDg2ZTEz 2x</value>
      <webElementGuid>fac2c656-e305-4b6e-a2a8-389d62e84761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Kitchen Appliances</value>
      <webElementGuid>37a558ee-8cc1-4c28-9072-27614b747718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/medias/Cooking-Appliances.png?context=bWFzdGVyfHJvb3R8NzY4NzR8aW1hZ2UvcG5nfGFEQm1MMmczT1M4eE1EVTVORFF3TlRZME5qTTJOaTlEYjI5cmFXNW5MVUZ3Y0d4cFlXNWpaWE11Y0c1bnxiMmUyYjgzYWQ3M2IyMDhkNjZhYjdmYTQ5ZGVlYTUxMjUwZjkxNjUyZmZlNGI0MjhkOGI3ZDlmOTQ1MDg2ZTEz 2x</value>
      <webElementGuid>ea2da188-f811-49bd-8f9b-1a58605c11e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>47ca47c4-1eed-479c-b9d4-033041c13587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-category&quot;)/ul[@class=&quot;ul-clear menu-category&quot;]/li[@class=&quot;lv1-li selected&quot;]/a[1]/figure[@class=&quot;responsive&quot;]/img[@class=&quot;lazy loaded&quot;]</value>
      <webElementGuid>ba00a880-ec9c-4d0c-a7b1-9da568c2a9a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='nav-menu-category']/ul[2]/li[5]/a/figure/img</value>
      <webElementGuid>7334d079-a73f-438f-b1d0-4bfa1aa8dae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Kitchen Appliances']</value>
      <webElementGuid>8e2e07d4-9289-42f3-ac95-e3d672cba05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/figure/img</value>
      <webElementGuid>99fa6075-1679-43f7-bf76-06df7cdc4640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Kitchen Appliances']</value>
      <webElementGuid>151cbd62-e886-492c-a4c9-63c7338d7a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='nav-menu-category']/ul[2]/li[4]/a/figure/img</value>
      <webElementGuid>00e95f69-a4b0-42a2-adc0-27a28c43c604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='LED TV']</value>
      <webElementGuid>0c27b6c3-90f4-4ff8-b1fa-ed215ec2e208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/figure/img</value>
      <webElementGuid>4609febc-c6d4-4e01-bc78-1a785d8b557e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'LED TV']</value>
      <webElementGuid>c514af25-b0c4-4380-96c6-83493dd780b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='nav-menu-category']/ul[2]/li[3]/a/figure/img</value>
      <webElementGuid>657ae965-cee8-48d9-8e9b-481203cbd16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Washing Machines']</value>
      <webElementGuid>b23f8140-de82-4195-a0c6-bf9d6eb9040c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/figure/img</value>
      <webElementGuid>441c1d7e-705d-4c7a-b8e6-45b45fb100ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Washing Machines']</value>
      <webElementGuid>3ad62ac5-cc6e-4dca-a3d4-f4d3198a5409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu']/ul[4]/li[2]/a/figure/img</value>
      <webElementGuid>e531dbf2-b023-41c2-808c-e39df8e6bd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Refrigerators and Freezers']</value>
      <webElementGuid>a62a4bc2-fa80-416c-9144-03e71cfdc3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>61454812-1ebd-405c-a77b-d9a7051df9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Refrigerators and Freezers']</value>
      <webElementGuid>66921831-8f10-4e22-b5da-652a64bab006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
