<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use_1_2</name>
   <tag></tag>
   <elementGuidId>5e7c1f4e-05fa-4f61-9389-c8e036419146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.icon.icon-bag > use</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>816019d1-e24c-4c30-9c2d-c674f9a9ce01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/_ui/shared/images/sprite-map.svg#bag</value>
      <webElementGuid>e9855181-4c14-4c8b-9da6-d043a0eb36bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;header-top se-item&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-3 col-lg-5 col-right&quot;]/a[@class=&quot;btn-cart&quot;]/svg[@class=&quot;icon icon-bag&quot;]/use[1]</value>
      <webElementGuid>acb9b022-069c-4ebd-b5d8-9e22615c9e57</webElementGuid>
   </webElementProperties>
</WebElementEntity>
