<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_lazy loaded</name>
   <tag></tag>
   <elementGuidId>7aa44895-4153-4e74-9ce8-4604a7086ab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-content-1']/ul/li[4]/a/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a > figure.responsive > img.lazy.loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d52e4e6-787a-4418-910e-3fc023839462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy loaded</value>
      <webElementGuid>367a5664-e4d3-430c-952d-870e302605ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>/medias/Image-6-250x250.png?context=bWFzdGVyfHJvb3R8MTc3MDl8aW1hZ2UvcG5nfGFHVTFMMmcxTlM4eE1EVTVPRGt4TkRreE5qTTRNaTlKYldGblpTQTJJQzBnTWpVd2VESTFNQzV3Ym1jfGY4N2E0MWE0Mjc3ZGU5ZGE1ZDUxNjQ3YWNiMDZmZjRiNGM1YmEyMDhjZGM4NDgxYmMyZDNjNzUxM2MzYmQwNjE 1x</value>
      <webElementGuid>15c6674b-328d-4ffd-9448-5aadda45def4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/medias/Image-6-250x250.png?context=bWFzdGVyfHJvb3R8MTc3MDl8aW1hZ2UvcG5nfGFHVTFMMmcxTlM4eE1EVTVPRGt4TkRreE5qTTRNaTlKYldGblpTQTJJQzBnTWpVd2VESTFNQzV3Ym1jfGY4N2E0MWE0Mjc3ZGU5ZGE1ZDUxNjQ3YWNiMDZmZjRiNGM1YmEyMDhjZGM4NDgxYmMyZDNjNzUxM2MzYmQwNjE 1x</value>
      <webElementGuid>1546d6c8-df6f-4297-bb8f-1448800f3ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6f3252b-7ed9-4f16-94ac-a4112b4579bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-content-1&quot;)/ul[@class=&quot;ul-clear category-list&quot;]/li[4]/a[1]/figure[@class=&quot;responsive&quot;]/img[@class=&quot;lazy loaded&quot;]</value>
      <webElementGuid>da874843-711f-4d79-9fe0-ea50e8267cbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li[4]/a/figure/img</value>
      <webElementGuid>8e8d32f4-a357-454c-8099-31dfc5a6a8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a/figure/img</value>
      <webElementGuid>b369474c-cb13-4710-9286-178833509849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li[3]/a/figure/img</value>
      <webElementGuid>f412d75f-b52c-42f5-9026-c082019fadb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a/figure/img</value>
      <webElementGuid>605b84cd-ef65-4709-bf95-682f268106e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li[2]/a/figure/img</value>
      <webElementGuid>efb9ade1-c205-47b6-a1ac-9784d8ea3cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a/figure/img</value>
      <webElementGuid>7ddc7a2b-98f0-4b61-a787-cf21f2f018e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-content-1']/ul/li/a/figure/img</value>
      <webElementGuid>d61ae779-8761-4319-ba0b-e84cccdfb842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/figure/img</value>
      <webElementGuid>6d7674d2-cf40-41b2-817f-1a14f8f4a37c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
